version: '3.8'

services:
  db:
    image: postgres:15
    container_name: shopify_postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - odoo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:17.0
    container_name: shopify_odoo17
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
      - "8072:8072"  # longpolling
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DB_NAME=odoo17_shopify
    volumes:
      # Monte le module dans les addons
      - ./:/mnt/extra-addons/shopify_integration:ro
      # Data persistante
      - odoo-web-data:/var/lib/odoo
      # Config custom
      - ./docker/odoo.conf:/etc/odoo/odoo.conf:ro
    networks:
      - odoo-network
    command: --
      --dev=all
      --log-level=info
      --workers=0
      --max-cron-threads=0
    restart: unless-stopped

volumes:
  odoo-db-data:
    driver: local
  odoo-web-data:
    driver: local

networks:
  odoo-network:
    driver: bridge